// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBgqFDoIco9V7pgHvRzs9ls7tE1CmYQsc',
    appId: '1:272762321955:web:b8c94db135575cadc80596',
    messagingSenderId: '272762321955',
    projectId: 'gdsc-fambal',
    authDomain: 'gdsc-fambal.firebaseapp.com',
    storageBucket: 'gdsc-fambal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3vfU2TVPYFfo3jjBDsCjR9SUrrwepcwc',
    appId: '1:272762321955:android:089c0abc195f67f9c80596',
    messagingSenderId: '272762321955',
    projectId: 'gdsc-fambal',
    storageBucket: 'gdsc-fambal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD891EsHB2SGtJnUxqF0NqIELQ2e3SNnLI',
    appId: '1:272762321955:ios:2cbb6068d7c6d62dc80596',
    messagingSenderId: '272762321955',
    projectId: 'gdsc-fambal',
    storageBucket: 'gdsc-fambal.appspot.com',
    iosBundleId: 'com.example.hacktonProject',
  );
}
